learm:

  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position controllers
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint1

  # Allow controller_manager controller_group to configure several controllers at once
  controller_groups:
    all:
      - joint_state_controller
      - joint1_position_controller
