learm:

  # Publish all joint states------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Effort controllers------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint1
